In [3]:
import numpy as np
from sklearn.cluster import KMeans

In [4]:
points = np.array([[0.1, 0.6],
                   [0.15, 0.71],
                   [0.08, 0.9],
                   [0.16, 0.85],
                   [0.2, 0.3],
                   [0.25, 0.5],
                   [0.24, 0.1],
                   [0.3, 0.2]])

In [7]:
intial_centroid = np.array([[0.1, 0.6],[0.3, 0.2]])

In [9]:
kmean = KMeans(n_clusters=2,init=intial_centroid,n_init=1).fit(points)

In [10]:
p6 = kmean.predict([[0.25, 0.5]])

In [11]:
p6

array([0], dtype=int32)

In [16]:
population = np.sum(kmean.labels_==1)

In [17]:
population

3

In [18]:
update_centre = kmean.cluster_centers_



In [19]:
update_centre[0]

array([0.148, 0.712])

In [20]:
update_centre[1]

array([0.24666667, 0.2       ])